### ISSUE TITLE
Create/Manage a docker environment to allow graftwerk to read/write on specific location

### ISSUE THREAD

**Issue by nivemaham** [datagraft/graftwerk#2]
We allow graftwerk to read and write files. Add OS level permission to restrict to specified location.

**Comment by fungiboletus** [comment]
I tried to make it work but not successfully. If you restrict the file permissions in the `.java.policy` file, it looks like `clojail` cannot grant any `java.io.FilePermission` even if the path is granted in the policy file. It sounds like a bug that will never be fixed as `java.security.Policy` has been removed from the latest Java version.

**Comment by nivemaham** [comment]
Thanks for trying :)
